
project_id = "hamqupvdhlfznwnuohsh"

[functions.send-certification]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true

[functions.ask-pulsebot]
verify_jwt = false

[functions.mailchimp-webhook]
verify_jwt = false

[functions.log-booking]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false
