import React, { useState, useRef, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Button } from "@/components/ui/button";
import { Download, DownloadCloud, Loader2, RefreshCw } from 'lucide-react';
import { useToast } from "@/hooks/use-toast";
import { useScreenshot } from 'use-react-screenshot';
import { BadgeStyle, BadgeType } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import { certificationService } from '@/services/certificationService';
import { useConfettiStore } from '@/stores/useConfettiStore';
import { useDashboard } from '@/contexts/DashboardContext';
import { useOnboarding } from '@/hooks/useOnboarding';
import { Progress } from "@/components/ui/progress";
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { Card, CardContent } from "@/components/ui/card";

interface BadgeGeneratorProps {
  badgeType: BadgeType;
  badgeStyle: BadgeStyle;
  companyName: string;
  showcaseUrl: string;
  employeeCount: number;
  pulseScore: number;
  onStyleChange: (style: BadgeStyle) => void;
}

const BadgeGenerator: React.FC<BadgeGeneratorProps> = ({
  badgeType,
  badgeStyle,
  companyName,
  showcaseUrl,
  employeeCount,
  pulseScore,
  onStyleChange
}) => {
  const { user, profile } = useAuth();
  const { toast } = useToast();
  const { setConfetti } = useConfettiStore();
  const { refreshData } = useDashboard();
  const { markStepComplete } = useOnboarding();
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const [isCopied, setIsCopied] = useState(false);
  const [embedCode, setEmbedCode] = useState('');
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [isUploadComplete, setIsUploadComplete] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [uploadSuccess, setUploadSuccess] = useState(false);
  const [uploadMessage, setUploadMessage] = useState<string | null>(null);
  const [isUploaded, setIsUploaded] = useState(false);
  const [isEmbedReady, setIsEmbedReady] = useState(false);
  const [isSavingToProfile, setIsSavingToProfile] = useState(false);
  const [isProfileSaved, setIsProfileSaved] = useState(false);
  const [profileSaveError, setProfileSaveError] = useState<string | null>(null);
  const [profileSaveSuccess, setProfileSaveSuccess] = useState(false);
  const [profileSaveMessage, setProfileSaveMessage] = useState<string | null>(null);
  const [isJourneyComplete, setIsJourneyComplete] = useState(false);
  const [isJourneyStarted, setIsJourneyStarted] = useState(false);
  const [isJourneyContinued, setIsJourneyContinued] = useState(false);
  const [isJourneySkipped, setIsJourneySkipped] = useState(false);
  const [isJourneyCancelled, setIsJourneyCancelled] = useState(false);
  const [isJourneyFailed, setIsJourneyFailed] = useState(false);
  const [isJourneyLoading, setIsJourneyLoading] = useState(false);
  const [isJourneySuccess, setIsJourneySuccess] = useState(false);
  const [journeyMessage, setJourneyMessage] = useState<string | null>(null);
  const [journeyError, setJourneyError] = useState<string | null>(null);
  const [journeyProgress, setJourneyProgress] = useState(0);
  const [isJourneyProgressVisible, setIsJourneyProgressVisible] = useState(false);
  const [isJourneyButtonVisible, setIsJourneyButtonVisible] = useState(false);
  const [isJourneyButtonDisabled, setIsJourneyButtonDisabled] = useState(false);
  const [journeyButtonText, setJourneyButtonText] = useState('Complete Certification');
  const [journeyButtonIcon, setJourneyButtonIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonLoading, setIsJourneyButtonLoading] = useState(false);
  const [isJourneyButtonSuccess, setIsJourneyButtonSuccess] = useState(false);
  const [isJourneyButtonError, setIsJourneyButtonError] = useState(false);
  const [journeyButtonErrorText, setJourneyButtonErrorText] = useState<string | null>(null);
  const [journeyButtonSuccessText, setJourneyButtonSuccessText] = useState<string | null>(null);
  const [isJourneyButtonSkipped, setIsJourneyButtonSkipped] = useState(false);
  const [journeyButtonSkippedText, setJourneyButtonSkippedText] = useState<string | null>(null);
  const [isJourneyButtonCancelled, setIsJourneyButtonCancelled] = useState(false);
  const [journeyButtonCancelledText, setJourneyButtonCancelledText] = useState<string | null>(null);
  const [isJourneyButtonFailed, setIsJourneyButtonFailed] = useState(false);
  const [journeyButtonFailedText, setJourneyButtonFailedText] = useState<string | null>(null);
  const [isJourneyButtonStarted, setIsJourneyButtonStarted] = useState(false);
  const [journeyButtonStartedText, setJourneyButtonStartedText] = useState<string | null>(null);
  const [isJourneyButtonContinued, setIsJourneyButtonContinued] = useState(false);
  const [journeyButtonContinuedText, setJourneyButtonContinuedText] = useState<string | null>(null);
  const [isJourneyButtonComplete, setIsJourneyButtonComplete] = useState(false);
  const [journeyButtonCompleteText, setJourneyButtonCompleteText] = useState<string | null>(null);
  const [isJourneyButtonLoadingText, setJourneyButtonLoadingText] = useState<string | null>(null);
  const [isJourneyButtonSuccessText, setJourneyButtonSuccessText] = useState<string | null>(null);
  const [isJourneyButtonErrorText, setJourneyButtonErrorText] = useState<string | null>(null);
  const [isJourneyButtonSkippedText, setJourneyButtonSkippedText] = useState<string | null>(null);
  const [isJourneyButtonCancelledText, setJourneyButtonCancelledText] = useState<string | null>(null);
  const [isJourneyButtonFailedText, setJourneyButtonFailedText] = useState<string | null>(null);
  const [isJourneyButtonStartedText, setJourneyButtonStartedText] = useState<string | null>(null);
  const [isJourneyButtonContinuedText, setJourneyButtonContinuedText] = useState<string | null>(null);
  const [isJourneyButtonCompleteText, setJourneyButtonCompleteText] = useState<string | null>(null);
  const [isJourneyButtonLoadingIcon, setJourneyButtonLoadingIcon] = useState<React.ReactNode>(<Loader2 className="ml-1 h-4 w-4 animate-spin" />);
  const [isJourneyButtonSuccessIcon, setJourneyButtonSuccessIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonErrorIcon, setJourneyButtonErrorIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonSkippedIcon, setJourneyButtonSkippedIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonCancelledIcon, setJourneyButtonCancelledIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonFailedIcon, setJourneyButtonFailedIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonStartedIcon, setJourneyButtonStartedIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonContinuedIcon, setJourneyButtonContinuedIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonCompleteIcon, setJourneyButtonCompleteIcon] = useState<React.ReactNode>(<ArrowRight className="ml-1 h-4 w-4" />);
  const [isJourneyButtonLoadingDisabled, setIsJourneyButtonLoadingDisabled] = useState(false);
  const [isJourneyButtonSuccessDisabled, setIsJourneyButtonSuccessDisabled] = useState(false);
  const [isJourneyButtonErrorDisabled, setIsJourneyButtonErrorDisabled] = useState(false);
  const [isJourneyButtonSkippedDisabled, setIsJourneyButtonSkippedDisabled] = useState(false);
  const [isJourneyButtonCancelledDisabled, setIsJourneyButtonCancelledDisabled] = useState(false);
  const [isJourneyButtonFailedDisabled, setIsJourneyButtonFailedDisabled] = useState(false);
  const [isJourneyButtonStartedDisabled, setIsJourneyButtonStartedDisabled] = useState(false);
  const [isJourneyButtonContinuedDisabled, setIsJourneyButtonContinuedDisabled] = useState(false);
  const [isJourneyButtonCompleteDisabled, setIsJourneyButtonCompleteDisabled] = useState(false);
  const [isJourneyButtonLoadingVisible, setIsJourneyButtonLoadingVisible] = useState(false);
  const [isJourneyButtonSuccessVisible, setIsJourneyButtonSuccessVisible] = useState(false);
  const [isJourneyButtonErrorVisible, setIsJourneyButtonErrorVisible] = useState(false);
  const [isJourneyButtonSkippedVisible, setIsJourneyButtonSkippedVisible] = useState(false);
  const [isJourneyButtonCancelledVisible, setIsJourneyButtonCancelledVisible] = useState(false);
  const [isJourneyButtonFailedVisible, setIsJourneyButtonFailedVisible] = useState(false);
  const [isJourneyButtonStartedVisible, setIsJourneyButtonStartedVisible] = useState(false);
  const [isJourneyButtonContinuedVisible, setIsJourneyButtonContinuedVisible] = useState(false);
  const [isJourneyButtonCompleteVisible, setIsJourneyButtonCompleteVisible] = useState(false);
  const [isJourneyButtonLoadingTextVisible, setIsJourneyButtonLoadingTextVisible] = useState(false);
  const [isJourneyButtonSuccessTextVisible, setIsJourneyButtonSuccessTextVisible] = useState(false);
  const [isJourneyButtonErrorTextVisible, setIsJourneyButtonErrorTextVisible] = useState(false);
  const [isJourneyButtonSkippedTextVisible, setIsJourneyButtonSkippedTextVisible] = useState(false);
  const [isJourneyButtonCancelledTextVisible, setIsJourneyButtonCancelledTextVisible] = useState(false);
  const [isJourneyButtonFailedTextVisible, setIsJourneyButtonFailedTextVisible] = useState(false);
  const [isJourneyButtonStartedTextVisible, setIsJourneyButtonStartedTextVisible] = useState(false);
  const [isJourneyButtonContinuedTextVisible, setIsJourneyButtonContinuedTextVisible] = useState(false);
  const [isJourneyButtonCompleteTextVisible, setIsJourneyButtonCompleteTextVisible] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIsJourneyButtonContinuedIconVisible] = useState(false);
  const [isJourneyButtonCompleteIconVisible, setIsJourneyButtonCompleteIconVisible] = useState(false);
  const [isJourneyButtonLoadingIconDisabled, setIsJourneyButtonLoadingIconDisabled] = useState(false);
  const [isJourneyButtonSuccessIconDisabled, setIsJourneyButtonSuccessIconDisabled] = useState(false);
  const [isJourneyButtonErrorIconDisabled, setIsJourneyButtonErrorIconDisabled] = useState(false);
  const [isJourneyButtonSkippedIconDisabled, setIsJourneyButtonSkippedIconDisabled] = useState(false);
  const [isJourneyButtonCancelledIconDisabled, setIsJourneyButtonCancelledIconDisabled] = useState(false);
  const [isJourneyButtonFailedIconDisabled, setIsJourneyButtonFailedIconDisabled] = useState(false);
  const [isJourneyButtonStartedIconDisabled, setIsJourneyButtonStartedIconDisabled] = useState(false);
  const [isJourneyButtonContinuedIconDisabled, setIsJourneyButtonContinuedIconDisabled] = useState(false);
  const [isJourneyButtonCompleteIconDisabled, setIsJourneyButtonCompleteIconDisabled] = useState(false);
  const [isJourneyButtonLoadingIconVisible, setIsJourneyButtonLoadingIconVisible] = useState(false);
  const [isJourneyButtonSuccessIconVisible, setIsJourneyButtonSuccessIconVisible] = useState(false);
  const [isJourneyButtonErrorIconVisible, setIsJourneyButtonErrorIconVisible] = useState(false);
  const [isJourneyButtonSkippedIconVisible, setIsJourneyButtonSkippedIconVisible] = useState(false);
  const [isJourneyButtonCancelledIconVisible, setIsJourneyButtonCancelledIconVisible] = useState(false);
  const [isJourneyButtonFailedIconVisible, setIsJourneyButtonFailedIconVisible] = useState(false);
  const [isJourneyButtonStartedIconVisible, setIsJourneyButtonStartedIconVisible] = useState(false);
  const [isJourneyButtonContinuedIconVisible, setIs
